steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}:${SHORT_SHA}', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}:${SHORT_SHA}']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args: [
      'run', 'deploy', '${_API_SERVICE}',
      '--image', '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}:${SHORT_SHA}',
      '--region', '${_REGION}',
      '--platform', 'managed',
      '--allow-unauthenticated',
      '--port', '8080',
      '--set-env-vars', 'NODE_ENV=development',
      '--set-secrets', 'MONGODB_URI=chatrix-mongo-dev:latest,OPENAI_API_KEY=chatrix-openai-key:latest,JWT_SECRET=chatrix-jwt-dev:latest'
    ]

images:
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}:${SHORT_SHA}'

options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _REGION: europe-west1
  _REPOSITORY: chatrix-containers
  _API_SERVICE: chatrix-back

timeout: 1800s