# version: "3.8"

# services:
#   node-app:
#     build: .
#     env_file:
#       - .env
#     environment:
#       - NODE_ENV=production
#       - PORT=3000
#     restart: always
#     ports:
#       - "3000:3000"
#     networks:
#       - app-network

#   nginx:
#     image: nginx:latest
#     ports:
#       - "8080:80"
#     volumes:
#       - ./nginx.conf:/etc/nginx/nginx.conf:ro
#       - ./static:/usr/share/nginx/html
#     depends_on:
#       - node-app
#     restart: always
#     networks:
#       - app-network

# networks:
#   app-network:
#     driver: bridge

version: "3.8"

services:
  app:
    build: .
    container_name: express-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    networks:
      - app-network

  nginx:
    image: nginx:stable-alpine
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
